DROP DATABASE IF EXISTS db_1;
CREATE DATABASE db_1;


DROP TABLE IF EXISTS db_1.user;
CREATE TABLE db_1.user (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL UNIQUE,
	email VARCHAR(200) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,

	PRIMARY KEY (ID)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS db_1.post;
CREATE TABLE db_1.post (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	user VARCHAR(100) NOT NULL,
	title VARCHAR(100) NOT NULL,
	description TEXT(500) NOT NULL,
	body TEXT NOT NULL,

	PRIMARY KEY (ID)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS db_1.comment;
CREATE TABLE db_1.comment (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	user VARCHAR(100) NOT NULL,
	post_id INT(11) NOT NULL,
	body TEXT(2000) NOT NULL,

	PRIMARY KEY (ID)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS db_1.relation;
CREATE TABLE db_1.relation (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	from_user VARCHAR(100) NOT NULL,
	to_user VARCHAR(100) NOT NULL,

	PRIMARY KEY (ID)
) ENGINE = InnoDB; 